### ISSUE TITLE
ExecuteInEditMode compatibility

### ISSUE THREAD

**Issue by JohannesMP** [jagt/unity3d-runtime-debug-draw#2]
Currently when used in a MonoBehavour that is set with [[ExecuteInEditModeAttribute](https://docs.unity3d.com/ScriptReference/ExecuteInEditMode.html)]:

```c#
[ExecuteInEditMode]
public class Tester : MonoBehaviour
{
  void Update()
  {
    RuntimeDebugDraw.Draw.DrawLine(Vector3.zero, Vector3.one);
  }
}
```

Results in several exceptions:

```c#
NullReferenceException: Object reference not set to an instance of an object
RuntimeDebugDraw.Internal.RuntimeDebugDraw.DrawTextOnDrawGizmos () (at Assets/RuntimeDebugDraw.cs:826)
RuntimeDebugDraw.Internal.RuntimeDebugDraw.OnDrawGizmos () (at Assets/RuntimeDebugDraw.cs:386)
UnityEditor.DockArea:OnGUI()
```

While adapting the library to work in-editor (when not in play mode) would take a good bit of work, at the very least calls to `RuntimeDebugDraw.Draw.`... should probably just silently fail.

------

Tested in Unity 5.6.1f1 windows 64bit

**Comment by jagt** [comment]
Thanks I'll merge this now and do a bit cleanup later!
