### ISSUE TITLE
Exit play mode causes intermittent error

### ISSUE THREAD

**Issue by LaneF** [jagt/unity3d-runtime-debug-draw#5]
Full error dump, Unity 2017.2.1f1

    Can't destroy Transform component of '________HIDDEN_C4F6A87F298241078E21C0D7C1D87A76_'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
    0x00000001411BA3EB (Unity) StackWalker::GetCurrentCallstack
    0x00000001411BCD7F (Unity) StackWalker::ShowCallstack
    0x0000000141097490 (Unity) GetStacktrace
    0x0000000140598663 (Unity) DebugStringToFile
    0x0000000140598E41 (Unity) DebugStringToFile
    0x00000001405D9A4C (Unity) DestroyObjectHighLevel
    0x00000001405F849F (Unity) DestroyWorldObjects
    0x0000000140B88266 (Unity) EditorSceneManager::RestoreSceneBackups
    0x00000001410CD86A (Unity) PlayerLoopController::ExitPlayMode
    0x00000001410CDEF0 (Unity) PlayerLoopController::SetIsPlaying
    0x00000001410CED42 (Unity) Application::TickTimer
    0x00000001412D7D39 (Unity) MainMessageLoop
    0x00000001412D95F4 (Unity) WinMain
    0x0000000141DF6538 (Unity) __tmainCRTStartup
    0x0000000076D759CD (kernel32) BaseThreadInitThunk
    0x0000000076FD383D (ntdll) RtlUserThreadStart

Looks like it happens when it's trying to clean up the object.

Does not seem to reproduce if I modify the hide flags to include the childgo

    // Existing
    go.hideFlags = HideFlags.HideAndDontSave;
    // Added new
    childGo.hideFlags = HideFlags.HideAndDontSave;

**Comment by jagt** [comment]
Hacked around it with 53e1a39 . I'm not sure what's causing it, but if I changed it to the way you suggested the drawing seems to be broken for me...
